version: "3"

services:
  # Webserver
  webserver:
    build:
      context: ./docker/bin/php74
    container_name: "laravel_service_repository_pattern_app"
    restart: 'always'
    ports:
      - "${WEBSERVER_PORT}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel_service_repository_pattern_network

  # Mysql
  mysql:
    build:
      context: ./docker/bin/mysql
    container_name: "laravel_service_repository_pattern_mysql"
    restart: 'always'
    ports:
      - "0.0.0.0:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - laravel_service_repository_pattern_network

  # Phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "laravel_service_repository_pattern_phpmyadmin"
    restart: 'always'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    ports:
      - '${HOST_MACHINE_PMA_PORT}:80'
    volumes:
      - /sessions
      - ${PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    networks:
      - laravel_service_repository_pattern_network

# Networks
networks:
  laravel_service_repository_pattern_network:
    driver: bridge

